#!/usr/bin/env python3
"""
collect_metrics.py

Data-collection script for the "Empirical Capacity Planning and Predictive
Workload Modeling" study (network-camera variant: phones used as RTSP/HTTP
IP cameras instead of USB webcams).

Design goals vs. the original script:
  - Supports 1-4 simultaneous camera streams (not hardcoded to one).
  - Logs the independent variables of the study as columns on every row
    (run_id, camera count, target resolution, target fps, motion label),
    so runs can be concatenated into one master CSV and modeled directly
    with the variable table in the proposal (N, W x H, FPS, mu).
  - Adds the dependent-variable metrics that were previously missing:
      * RAM resident set size (this process) + swap usage (not just
        "RAM used" system-wide)
      * Kernel interrupt count delta (/proc/interrupts) as an IRQ overhead
        proxy (replaces the USB-bus-specific IRQ idea, since the workload
        is now network-attached, not USB-attached)
      * iowait % (from /proc/stat) and disk write throughput/IOPS
        (from /proc/diskstats) for the storage subsystem
      * Network throughput (RX/TX bytes/s) and RX errors/drops per
        interface, which is the network-camera analogue of "USB bus
        saturation" in the original proposal
      * Per-camera capture latency (wall-clock time spent in .grab())
      * Frame loss rate (drops / (drops + frames)), not just a raw
        drop counter
  - Uses cap.grab() instead of cap.read() for the capture loop: grab()
    only demuxes/receives a frame from the stream, it does not decode it
    to a pixel array. Since this script never inspects frame content
    (no motion analysis, no recording), decoding every frame with
    read()/retrieve() was pure wasted CPU -- avoiding it matters a lot
    once you're running 4 concurrent 1080p streams.
  - Scene activity (mu / motion_label) can't be generated by software when
    it's a physically staged scene, so it's accepted as a required CLI
    argument and stamped on every row instead of being silently absent.

Usage:
    python3 data_collector.py \
        --cameras rtsp://192.168.100.108:8080/h264_aac.sdp\
        --run-id N2_720p_30fps_dynamic \
        --target-resolution 1280x720 \
        --target-fps 30 \
        --motion-label static \
        --duration-min 30 \
        --output test1.csv\

    # Quick local test without real cameras (uses your webcam / a test pattern):
    python3 collect_metrics.py --mock --duration-min 1 --output test.csv
"""

import argparse
import csv
import os
import re
import subprocess
import threading
import time
from datetime import datetime

import cv2
import psutil

os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"] = (
    "rtsp_transport;udp|fflags;nobuffer|flags;low_delay"
)


# ============================================================
# THREADED CAMERA (per-stream capture + per-frame latency)
# ============================================================

class ThreadedCamera:
    """
    Reads timing/arrival metadata from the stream WITHOUT decoding frames.

    This script never looks at pixel data (no motion analysis, no saving
    video), so calling cv2.VideoCapture.read() -- which grabs AND decodes
    every frame to a raw BGR array -- burns CPU for nothing. We use
    .grab() instead, which only demuxes/receives the next frame from the
    stream and skips the decode step (.retrieve()). This keeps FPS,
    latency, and drop measurements accurate (they depend on frame
    arrival, not frame content) while cutting CPU usage substantially,
    which matters a lot with 4 concurrent 1080p streams.
    """

    def __init__(self, url, mock=False):
        self.url = url
        self.mock = mock
        self.running = True
        self.ret = False

        self.frames = 0
        self.drops = 0
        self.fps = 0.0
        self.last_fps_calc = time.time()

        self.last_latency_ms = 0.0
        self._latency_sum_window = 0.0
        self._latency_n_window = 0

        if mock:
            self.cap = cv2.VideoCapture(0)  # local webcam / test device
        elif url.startswith(("rtsp://", "http://")):
            self.cap = cv2.VideoCapture(url, cv2.CAP_FFMPEG)
            self.cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
        else:
            self.cap = cv2.VideoCapture(url)

        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height = int(self.cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        self.resolution = f"{self.width}x{self.height}"

        self.thread = threading.Thread(target=self.update, daemon=True)
        self.thread.start()

    def update(self):
        while self.running:
            t0 = time.time()
            ret = self.cap.grab()  # demux/receive only -- no decode
            latency_ms = (time.time() - t0) * 1000.0

            if ret:
                self.ret = True
                self.frames += 1
                self._latency_sum_window += latency_ms
                self._latency_n_window += 1
            else:
                self.drops += 1

    def pop_window_stats(self):
        """Compute fps + mean capture latency since last call, then reset window."""
        now = time.time()
        elapsed = now - self.last_fps_calc
        if elapsed >= 1:
            self.fps = round(self.frames / elapsed, 2)
            self.frames = 0
            self.last_fps_calc = now

        if self._latency_n_window:
            self.last_latency_ms = round(
                self._latency_sum_window / self._latency_n_window, 2
            )
        self._latency_sum_window = 0.0
        self._latency_n_window = 0

        return self.fps, self.last_latency_ms

    def frame_loss_rate(self):
        total = self.frames + self.drops
        if total == 0:
            return 0.0
        return round(self.drops / total, 4)

    def stop(self):
        self.running = False
        self.cap.release()


# ============================================================
# SYSTEM METRIC HELPERS
# ============================================================

def temperature_c():
    try:
        with open("/sys/class/thermal/thermal_zone0/temp") as f:
            return round(int(f.read()) / 1000, 2)
    except Exception:
        return None


def cpu_freq_mhz():
    try:
        f = psutil.cpu_freq()
        return round(f.current, 1) if f else None
    except Exception:
        return None


def throttle_state():
    try:
        r = subprocess.check_output(["vcgencmd", "get_throttled"])
        return r.decode().strip()
    except Exception:
        return "N/A"


def process_rss_mb():
    try:
        return round(psutil.Process(os.getpid()).memory_info().rss / (1024 * 1024), 2)
    except Exception:
        return None


class DiskIRQNetSampler:
    """
    Tracks delta-based metrics that require two /proc reads a fixed
    interval apart: disk write throughput/IOPS, IRQ counts, iowait %,
    and per-interface network throughput/errors.
    """

    def __init__(self, disk_device_prefix="mmcblk", net_iface=None):
        self.disk_device_prefix = disk_device_prefix
        self.net_iface = net_iface or self._guess_iface()

        self._last_disk = self._read_diskstats()
        self._last_irq_total = self._read_irq_total()
        self._last_cpu_times = self._read_cpu_times()
        self._last_net = self._read_net_dev()
        self._last_t = time.time()

    def _guess_iface(self):
        # Prefer wlan0, then eth0, else first non-loopback interface found.
        try:
            with open("/proc/net/dev") as f:
                ifaces = [
                    line.split(":")[0].strip()
                    for line in f.readlines()[2:]
                    if ":" in line
                ]
            for pref in ("wlan0", "eth0"):
                if pref in ifaces:
                    return pref
            for i in ifaces:
                if i != "lo":
                    return i
        except Exception:
            pass
        return "wlan0"

    def _read_diskstats(self):
        stats = {}
        try:
            with open("/proc/diskstats") as f:
                for line in f:
                    parts = line.split()
                    dev = parts[2]
                    if self.disk_device_prefix in dev:
                        # fields: reads_completed(3) ... sectors_written(9) ... ms_writing(10)
                        stats[dev] = {
                            "writes_completed": int(parts[7]),
                            "sectors_written": int(parts[9]),
                        }
        except Exception:
            pass
        return stats

    def _read_irq_total(self):
        total = 0
        try:
            with open("/proc/interrupts") as f:
                for line in f.readlines():
                    nums = re.findall(r"\b\d+\b", line)
                    if nums and ":" in line.split()[0]:
                        total += sum(int(n) for n in nums)
        except Exception:
            pass
        return total

    def _read_cpu_times(self):
        try:
            with open("/proc/stat") as f:
                line = f.readline()
            vals = [int(x) for x in line.split()[1:]]
            # user nice system idle iowait irq softirq steal
            return vals
        except Exception:
            return None

    def _read_net_dev(self):
        stats = {}
        try:
            with open("/proc/net/dev") as f:
                for line in f.readlines()[2:]:
                    if ":" not in line:
                        continue
                    name, rest = line.split(":", 1)
                    name = name.strip()
                    f_ = rest.split()
                    stats[name] = {
                        "rx_bytes": int(f_[0]),
                        "rx_errs": int(f_[2]),
                        "rx_drop": int(f_[3]),
                        "tx_bytes": int(f_[8]),
                        "tx_errs": int(f_[10]),
                        "tx_drop": int(f_[11]),
                    }
        except Exception:
            pass
        return stats

    def sample(self):
        """Return a dict of delta-based metrics since the previous call."""
        now = time.time()
        elapsed = max(now - self._last_t, 1e-6)

        # --- disk ---
        disk_now = self._read_diskstats()
        write_kb_s = 0.0
        iops = 0.0
        for dev, cur in disk_now.items():
            prev = self._last_disk.get(dev)
            if prev:
                d_sectors = cur["sectors_written"] - prev["sectors_written"]
                d_writes = cur["writes_completed"] - prev["writes_completed"]
                write_kb_s += (d_sectors * 512 / 1024) / elapsed
                iops += d_writes / elapsed
        self._last_disk = disk_now

        # --- irq ---
        irq_now = self._read_irq_total()
        irq_per_s = (irq_now - self._last_irq_total) / elapsed
        self._last_irq_total = irq_now

        # --- iowait % ---
        cpu_now = self._read_cpu_times()
        iowait_pct = None
        if cpu_now and self._last_cpu_times:
            prev = self._last_cpu_times
            d = [c - p for c, p in zip(cpu_now, prev)]
            total = sum(d)
            iowait_pct = round(100 * d[4] / total, 2) if total > 0 else None
        self._last_cpu_times = cpu_now

        # --- network ---
        net_now = self._read_net_dev()
        rx_kb_s = tx_kb_s = 0.0
        rx_drop = tx_drop = 0
        cur_if = net_now.get(self.net_iface)
        prev_if = self._last_net.get(self.net_iface)
        if cur_if and prev_if:
            rx_kb_s = (cur_if["rx_bytes"] - prev_if["rx_bytes"]) / 1024 / elapsed
            tx_kb_s = (cur_if["tx_bytes"] - prev_if["tx_bytes"]) / 1024 / elapsed
            rx_drop = cur_if["rx_drop"] - prev_if["rx_drop"]
            tx_drop = cur_if["tx_drop"] - prev_if["tx_drop"]
        self._last_net = net_now

        self._last_t = now

        return {
            "disk_write_KBs": round(write_kb_s, 2),
            "disk_iops": round(iops, 2),
            "irq_per_s": round(irq_per_s, 2),
            "iowait_pct": iowait_pct,
            "net_iface": self.net_iface,
            "net_rx_KBs": round(rx_kb_s, 2),
            "net_tx_KBs": round(tx_kb_s, 2),
            "net_rx_drop": rx_drop,
            "net_tx_drop": tx_drop,
        }


# ============================================================
# MAIN
# ============================================================

FIELDNAMES = [
    "timestamp", "run_id", "n_cameras", "target_resolution", "target_fps",
    "motion_label", "elapsed_s",
    "camera", "actual_resolution", "cam_fps", "cam_drops", "cam_frame_loss_rate",
    "cam_capture_latency_ms",
    "cpu_pct", "cpu_freq_mhz", "ram_used_mb", "ram_available_mb", "swap_used_mb",
    "process_rss_mb", "temp_c", "throttle",
    "iowait_pct", "disk_write_KBs", "disk_iops", "irq_per_s",
    "net_iface", "net_rx_KBs", "net_tx_KBs", "net_rx_drop", "net_tx_drop",
    "threads",
]


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cameras", type=str, default="",
                    help="Comma-separated list of RTSP/HTTP camera URLs (1-4).")
    p.add_argument("--mock", action="store_true",
                    help="Use local webcam(s) instead of network cameras, for a dry run.")
    p.add_argument("--run-id", type=str, default=None,
                    help="Identifier for this run, e.g. N2_720p_30fps_dynamic. "
                         "Auto-generated from parameters if omitted.")
    p.add_argument("--target-resolution", type=str, default="unknown",
                    help="Resolution the phone camera app is set to, e.g. 1280x720. "
                         "Recorded as metadata; actual delivered resolution is measured separately.")
    p.add_argument("--target-fps", type=str, default="unknown",
                    help="FPS the phone camera app is set to, e.g. 30.")
    p.add_argument("--motion-label", type=str, required=True,
                    choices=["static", "stochastic", "dynamic"],
                    help="Scene-activity condition staged for this run (mu).")
    p.add_argument("--duration-min", type=float, default=30,
                    help="Run duration in minutes (30 = standard, 240 = thermal stress).")
    p.add_argument("--sample-hz", type=float, default=1.0,
                    help="Sampling frequency in Hz (default 1 Hz per proposal).")
    p.add_argument("--disk-device-prefix", type=str, default="mmcblk",
                    help="Substring to match the storage device in /proc/diskstats "
                         "(mmcblk for SD card, sda for USB/SSD).")
    p.add_argument("--net-iface", type=str, default=None,
                    help="Network interface to measure (default: auto-detect wlan0/eth0).")
    p.add_argument("--output", type=str, required=True, help="Output CSV path.")
    return p.parse_args()


def main():
    args = parse_args()

    if args.mock:
        urls = ["mock-local-webcam"]
    else:
        urls = [u.strip() for u in args.cameras.split(",") if u.strip()]
    if not urls:
        raise SystemExit("No cameras specified. Use --cameras or --mock.")
    if len(urls) > 4:
        raise SystemExit("This study's design matrix caps at 4 concurrent cameras.")

    run_id = args.run_id or (
        f"N{len(urls)}_{args.target_resolution}_{args.target_fps}fps_{args.motion_label}"
    )

    print(f"\n=== Run: {run_id} ===")
    print(f"Cameras ({len(urls)}): {urls}")
    print(f"Target resolution/fps (metadata): {args.target_resolution} / {args.target_fps}")
    print(f"Motion label: {args.motion_label}")
    print(f"Duration: {args.duration_min} min\n")

    cameras = []
    for url in urls:
        print("Connecting:", url)
        cam = ThreadedCamera(url, mock=args.mock)
        if cam.cap.isOpened():
            print("  Connected", cam.resolution)
            cameras.append(cam)
        else:
            print("  FAILED to open", url)

    if not cameras:
        print("No cameras connected. Exiting.")
        return

    sampler = DiskIRQNetSampler(
        disk_device_prefix=args.disk_device_prefix, net_iface=args.net_iface
    )

    out_dir = os.path.dirname(args.output)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    file_exists = os.path.exists(args.output) and os.path.getsize(args.output) > 0
    period = 1.0 / args.sample_hz
    end_time = time.time() + args.duration_min * 60
    start_time = time.time()

    with open(args.output, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        if not file_exists:
            writer.writeheader()

        print("Monitoring started. Ctrl+C to stop early.\n")
        try:
            while time.time() < end_time:
                loop_start = time.time()

                cpu_pct = psutil.cpu_percent()
                vm = psutil.virtual_memory()
                sw = psutil.swap_memory()
                sample = sampler.sample()

                shared = {
                    "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "run_id": run_id,
                    "n_cameras": len(cameras),
                    "target_resolution": args.target_resolution,
                    "target_fps": args.target_fps,
                    "motion_label": args.motion_label,
                    "elapsed_s": round(time.time() - start_time, 1),
                    "cpu_pct": cpu_pct,
                    "cpu_freq_mhz": cpu_freq_mhz(),
                    "ram_used_mb": round(vm.used / (1024 * 1024), 1),
                    "ram_available_mb": round(vm.available / (1024 * 1024), 1),
                    "swap_used_mb": round(sw.used / (1024 * 1024), 1),
                    "process_rss_mb": process_rss_mb(),
                    "temp_c": temperature_c(),
                    "throttle": throttle_state(),
                    "iowait_pct": sample["iowait_pct"],
                    "disk_write_KBs": sample["disk_write_KBs"],
                    "disk_iops": sample["disk_iops"],
                    "irq_per_s": sample["irq_per_s"],
                    "net_iface": sample["net_iface"],
                    "net_rx_KBs": sample["net_rx_KBs"],
                    "net_tx_KBs": sample["net_tx_KBs"],
                    "net_rx_drop": sample["net_rx_drop"],
                    "net_tx_drop": sample["net_tx_drop"],
                    "threads": threading.active_count(),
                }

                for cam in cameras:
                    fps, latency_ms = cam.pop_window_stats()
                    row = dict(shared)
                    row.update({
                        "camera": cam.url,
                        "actual_resolution": cam.resolution,
                        "cam_fps": fps,
                        "cam_drops": cam.drops,
                        "cam_frame_loss_rate": cam.frame_loss_rate(),
                        "cam_capture_latency_ms": latency_ms,
                    })
                    writer.writerow(row)

                f.flush()

                print(
                    f"{shared['timestamp']} | run={run_id} | CPU={cpu_pct}% | "
                    f"TEMP={shared['temp_c']} | iowait={shared['iowait_pct']}% | "
                    f"net_rx={shared['net_rx_KBs']}KB/s | "
                    + " | ".join(f"{c.url.split('//')[-1][:15]}:{c.fps}fps" for c in cameras)
                )

                sleep_left = period - (time.time() - loop_start)
                if sleep_left > 0:
                    time.sleep(sleep_left)

        except KeyboardInterrupt:
            print("\nStopped early by user.")

        finally:
            for cam in cameras:
                cam.stop()

    print(f"\nRun complete. Data written to {args.output}")


if __name__ == "__main__":
    main()